Controllers/EnrollmentController.cs
using Microsoft.AspNetCore.Mvc;
using DemoMvc.AppDbContext;
using DemoMvc.Models;

namespace DemoMvc.Controllers
{
	public class EnrollmentController : Controller
	{
		private DemoEducationaldbContext con = new DemoEducationaldbContext();
		public IActionResult Index()
		{
			var enrolls = con.Courseentrollments.ToList();
			return View(enrolls);
		}

		[HttpGet]
		public IActionResult EnrollForCourse()
		{
			return PartialView("EnrollmentPartial");
		}

		[HttpPost]
		public IActionResult SaveEnroll(Courseentrollment Std_crs) {

			ModelState.Remove("CousreCourse");
			ModelState.Remove("StudentStudet");

			if (!ModelState.IsValid) {
				//return View("~/Views/Home/Index.cshtml");
				return View("EnrollmentPartial");
			}


			con.Courseentrollments.Add(Std_crs);
			con.SaveChanges();

			return RedirectToAction("Index");

			


		}

		public JsonResult ValidateStdID(int StudentStudetId)
		{
			var std = con.Students.FirstOrDefault(x => x.StudetId == StudentStudetId);

            if (std != null)
            {
				return Json(true);
            }

			return Json(false);
        }

		public JsonResult ValidateCrsID(int CrsId) {

			var crs = con.Cousres.FirstOrDefault(x => x.CourseId == CrsId);

			if (crs != null) { 
				return Json(true);
			}

			return Json(false);
		}
	}
}

Views/Enrollment/EnrollmentPartial.cshtml
@model Courseentrollment

<form class="form-control" asp-action="SaveEnroll" asp-controller="Enrollment" method="post">

	<label asp-for="CousreCourseId" class="form-label"></label>
	<input class="form-control" asp-for="CousreCourseId"></input>
	<span asp-validation-for="CousreCourseId" class="text-danger"></span>

	<br></br>

	<label asp-for="StudentStudetId" class="form-label"></label>
	<input class="form-control" asp-for="StudentStudetId"></input>
	<span asp-validation-for="StudentStudetId" class="text-danger"></span>

	<br></br>


	<label asp-for="Degree" class="form-label"></label>
	<input class="form-control" asp-for="Degree"></input>
	<span asp-validation-for="Degree" class="text-danger"></span>
	<br><br>
	<input type="submit" class="btn-success"></input>

</form>

@section scripts{
	<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

	<script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
	<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

Views/Enrollment/Index.cshtml
@model List<Courseentrollment>
<table class="table">
	<thead>
		<th>StudentID</th>
		<th>CourseID</th>
		<th>Degree</th>
	</thead>

	<tbody>
		@foreach(var item in Model)
		{
			<tr>
				<td>@item.StudentStudetId</td>
				<td>@item.CousreCourseId</td>
				<td>@item.Degree</td>
			</tr>
			
		}
	</tbody>
</table>